version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u171-jdk
      - image: redislabs/redisgraph:edge

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
        
     # - run: mvn pmd:check
      - run: mvn integration-test 
      - run: mvn cobertura:cobertura
      - run: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}  
      - run: mvn -s .circleci.settings.xml -DskipTests deploy

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build

